DROP DATABASE IF EXISTS sdc;

CREATE DATABASE sdc;

USE sdc;
		
CREATE TABLE IF NOT EXISTS Products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Reviews (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id INT UNSIGNED NOT NULL,
  rating TINYINT NOT NULL,
  review_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  summary VARCHAR(50) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  recommend BOOLEAN NOT NULL,
  reported BOOLEAN NOT NULL,
  reviewer_name VARCHAR(30) NOT NULL,
  reviewer_email VARCHAR(60) NOT NULL,
  response VARCHAR(100),
  helpfulness TINYINT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (product_id) REFERENCES Products(id) ON DELETE CASCADE
);
		
CREATE TABLE IF NOT EXISTS Characteristics (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id INT UNSIGNED NOT NULL,
  characteristic_name VARCHAR(20) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (product_id) REFERENCES Products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Characteristic_Reviews (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  characteristic_id INT UNSIGNED NOT NULL,
  review_id INT UNSIGNED NOT NULL,
  characteristic_value INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (review_id) REFERENCES Reviews(id) ON DELETE CASCADE,
  FOREIGN KEY (characteristic_id) REFERENCES Characteristics(id) ON DELETE CASCADE
);
		
CREATE TABLE IF NOT EXISTS Photos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  review_id INT UNSIGNED NOT NULL,
  photo_url VARCHAR(300) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (review_id) REFERENCES Reviews(id) ON DELETE CASCADE
)