DROP DATABASE IF EXISTS sdc;

USE sdc;

DROP TABLE IF EXISTS Products;
		
CREATE TABLE Products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Reviews;
		
CREATE TABLE Reviews (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id INT UNSIGNED NOT NULL,
  rating TINYINT NOT NULL,
  summary VARCHAR(50) NOT NULL,
  recommend BOOLEAN NOT NULL,
  response VARCHAR(1000),
  body VARCHAR(1000) NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewer_name VARCHAR(30) NOT NULL,
  reviewer_email VARCHAR(60) NOT NULL,
  helpfulness TINYINT NOT NULL,
  reported BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (product_id) REFERENCES Products (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Characteristics;
		
CREATE TABLE Characteristics (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id INT UNSIGNED NOT NULL,
  characteristic_name VARCHAR(20) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (product_id) REFERENCES Products (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Characteristic_Reviews;
		
CREATE TABLE Characteristic_Reviews (
  id INTEGER NOT NULL AUTO_INCREMENT,
  review_id INTEGER NULL,
  characteristic_id INTEGER NOT NULL,
  value VARCHAR NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (review_id) REFERENCES Reviews (id) ON DELETE CASCADE,
  FOREIGN KEY (characteristic_id) REFERENCES Characteristics (id) ON DELETE CASCADE
);


DROP TABLE IF EXISTS Photos;
		
CREATE TABLE Photos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  photo_url VARCHAR(1000) NULL,
  review_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (review_id) REFERENCES Reviews (id) ON DELETE CASCADE
)